$("#fd").click(function fakeFormData() {
        $('#first_name').val('Aditya');
        $('#last_name').val('Kulshrstha');
        $('#birth_date').val('2004-05-08');
        $('#phone').val('7840869129');
        $('#email').val('aditya.kulshrestha@outlook.com');
        $('#city').val('Noida');
        $('#employer').val('Shiv Nadar School Noida');
        $('#ex_employer1').val('Amity International School Vasundhra');
        $('#ex_employer2').val('Rainbow Preschool');
        $('#subjects').val('Computer Science, Mathematics, Physics, Chemistry');
        $('#curriculum').val('CBSE, ICSE');
        $('#class_size').val(45);
        $('#participatereason').val('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque lectus lorem, ornare a erat vitae, tempor efficitur ex. Fusce tempor finibus venenatis. Nulla eget sapien quis purus sodales ullamcorper. Integer sed nunc vel lacus lacinia scelerisque ac ut libero. Donec vestibulum sem ligula, ut molestie est blandit ac. Sed accumsan id odio non vehicula. Proin et magna ligula. Fusce interdum quam vitae tristique consectetur. Morbi et dignissim ex. Praesent quam eros, venenatis ut massa vitae, cursus lobortis justo. Vivamus sodales ipsum sit amet quam gravida bibendum. Donec posuere condimentum enim, sed lobortis dolor. Suspendisse blandit maximus enim, et porttitor orci lobortis sit amet. Nunc iaculis lorem eget lacus condimentum, vitae lacinia leo facilisis. Nam ac dignissim nunc. Quisque quis augue viverra, porttitor nisi dignissim, condimentum magna. Vivamus eu porta ligula, sed aliquet augue. Sed eleifend tincidunt nunc at egestas. Integer sed cursus nulla. Integer hendrerit magna eu lectus facilisis tristique. Donec aliquam pretium diam laoreet egestas. Praesent aliquet neque felis, nec ultricies risus tristique non. Praesent pulvinar, magna a luctus ultrices, lorem augue porta magna, et tincidunt magna ipsum at lectus. Sed erat nunc, vulputate ac risus et, luctus viverra mi. Donec ut scelerisque sapien, a rutrum enim. Maecenas ac maximus felis. Aliquam erat volutpat. Sed turpis nibh, elementum ac lacus in, pellentesque porttitor ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus dapibus maximus luctus. Integer accumsan porttitor leo, eu mattis nulla efficitur id. Donec pulvinar est sed euismod pellentesque. Pellentesque sollicitudin ipsum.');
        $('#conceptteaching').val('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque lectus lorem, ornare a erat vitae, tempor efficitur ex. Fusce tempor finibus venenatis. Nulla eget sapien quis purus sodales ullamcorper. Integer sed nunc vel lacus lacinia scelerisque ac ut libero. Donec vestibulum sem ligula, ut molestie est blandit ac. Sed accumsan id odio non vehicula. Proin et magna ligula. Fusce interdum quam vitae tristique consectetur. Morbi et dignissim ex. Praesent quam eros, venenatis ut massa vitae, cursus lobortis justo. Vivamus sodales ipsum sit amet quam gravida bibendum. Donec posuere condimentum enim, sed lobortis dolor. Suspendisse blandit maximus enim, et porttitor orci lobortis sit amet. Nunc iaculis lorem eget lacus condimentum, vitae lacinia leo facilisis. Nam ac dignissim nunc. Quisque quis augue viverra, porttitor nisi dignissim, condimentum magna. Vivamus eu porta ligula, sed aliquet augue. Sed eleifend tincidunt nunc at egestas. Integer sed cursus nulla. Integer hendrerit magna eu lectus facilisis tristique. Donec aliquam pretium diam laoreet egestas. Praesent aliquet neque felis, nec ultricies risus tristique non. Praesent pulvinar, magna a luctus ultrices, lorem augue porta magna, et tincidunt magna ipsum at lectus. Sed erat nunc, vulputate ac risus et, luctus viverra mi. Donec ut scelerisque sapien, a rutrum enim. Maecenas ac maximus felis. Aliquam erat volutpat. Sed turpis nibh, elementum ac lacus in, pellentesque porttitor ex. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus dapibus maximus luctus. Integer accumsan porttitor leo, eu mattis nulla efficitur id. Donec pulvinar est sed euismod pellentesque. Pellentesque sollicitudin ipsum.');
        $('#apply1').val('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor volutpat magna, in fringilla lectus fermentum at. Aenean mattis turpis ex, quis tempus quam hendrerit. ');
        $('#apply2').val('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor volutpat magna, in fringilla lectus fermentum at. Aenean mattis turpis ex, quis tempus quam hendrerit. ');
        $('#apply3').val('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut auctor volutpat magna, in fringilla lectus fermentum at. Aenean mattis turpis ex, quis tempus quam hendrerit. ');
        // $('#first_name').val('');
        // $('#last_name').val('');
        // $('#birth_date').val('');
        // $('#phone').val('');
        // $('#email').val('');
        // $('#city').val('');
        // $('#employer').val('');
        // $('#ex_employer1').val('');
        // $('#ex_employer2').val('');
        // $('#subjects').val('');
        // $('#curriculum').val('');
        // $('#class_size').val('');
        // $('#participatereason').val('');
        // $('#conceptteaching').val('');
        // $('#apply1').val('');
        // $('#apply2').val('');
        // $('#apply3').val('');
});